# Generated by Django 6.0.6 on 2026-06-10 23:00

import apps.maestros.models.empresa_models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaMutual',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_cuenta_mutual', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_cuenta_mutual', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus*')),
                ('id_socio', models.IntegerField(blank=True, null=True, verbose_name='ID Socio*')),
                ('cuenta', models.BigIntegerField(blank=True, db_index=True, unique=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI')),
                ('cuit', models.CharField(blank=True, max_length=11, null=True, verbose_name='CUIT')),
                ('razon_social', models.CharField(blank=True, max_length=80, null=True, verbose_name='Razón Social')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario')], max_length=1, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('caracteristica_pais_telefono', models.CharField(blank=True, default=54, max_length=2, null=True)),
                ('codigo_area_telefono', models.CharField(blank=True, max_length=4, null=True)),
                ('numero_telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('id_sg_usuario', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('id_sg_cuenta', models.CharField(blank=True, max_length=36, null=True, unique=True)),
                ('cvu', models.CharField(blank=True, max_length=22, null=True, unique=True)),
                ('alias', models.CharField(blank=True, max_length=60, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Cuenta Mutual',
                'verbose_name_plural': 'Cuentas Mutuales',
                'db_table': 'cuenta_mutual',
                'ordering': ['id_cuenta_mutual'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_empresa', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus*')),
                ('nombre_fiscal', models.CharField(max_length=50, verbose_name='Nombre Fiscal*')),
                ('nombre_comercial', models.CharField(max_length=50, verbose_name='Nombre Comercial*')),
                ('domicilio_empresa', models.CharField(max_length=50, verbose_name='Domicilio*')),
                ('codigo_postal', models.CharField(max_length=4, verbose_name='Código postal*')),
                ('cuit', models.BigIntegerField(verbose_name='C.U.I.T.*')),
                ('ingresos_bruto', models.CharField(max_length=15, verbose_name='Ing. Bruto*')),
                ('inicio_actividad', models.DateField(verbose_name='Inicio de actividad*')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono*')),
                ('email_empresa', models.EmailField(max_length=50, verbose_name='Correo*')),
                ('web_empresa', models.CharField(blank=True, max_length=50, null=True, verbose_name='Web')),
                ('logo_empresa', models.ImageField(blank=True, help_text='Formatos permitidos: JPG, PNG, GIF. Tamaño máximo: 2MB', max_length=255, null=True, upload_to=apps.maestros.models.empresa_models.logo_upload_path, verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['nombre_fiscal'],
            },
        ),
        migrations.CreateModel(
            name='SgEntidadTipoDocumento',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_entidad_tipo_documento', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('estatus_sg_entidad_tipo_documento', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Entidad Tipo Documento')),
            ],
            options={
                'verbose_name': 'SG Entidad Tipo Documento',
                'verbose_name_plural': 'SG Entidad Tipo Documento',
                'db_table': 'sg_entidad_tipo_documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SgTipoCuenta',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_tipo_cuenta', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('estatus_sg_tipo_cuenta', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('tipo_cuenta', models.CharField(max_length=60, verbose_name='Tipo Cuenta')),
            ],
            options={
                'verbose_name': 'SG Tipo Cuenta',
                'verbose_name_plural': 'SG Tipos Cuentas',
                'db_table': 'sg_tipo_cuenta',
                'ordering': ['tipo_cuenta'],
            },
        ),
        migrations.CreateModel(
            name='SgTipoPersona',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_tipo_persona', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('estatus_sg_tipo_persona', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('tipo_persona', models.CharField(max_length=60, verbose_name='Tipo Persona')),
            ],
            options={
                'verbose_name': 'SG Tipo Persona',
                'verbose_name_plural': 'SG Tipos Personas',
                'db_table': 'sg_tipo_persona',
                'ordering': ['tipo_persona'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_sucursal', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre_sucursal', models.CharField(max_length=50, verbose_name='Nombre sucursal')),
                ('domicilio_sucursal', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('telefono_sucursal', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('email_sucursal', models.EmailField(max_length=50, verbose_name='Correo')),
                ('ws_url', models.CharField(max_length=50, verbose_name='WebService URL')),
                ('ws_token_acceso', models.CharField(max_length=50, verbose_name='Token Acceso')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
                'ordering': ['nombre_sucursal'],
            },
        ),
    ]
