# Generated by Django 6.0.6 on 2026-06-19 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SgConceptoTransaccion',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_concepto_transaccion', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Concepto Transacción')),
                ('estatus_sg_concepto_transaccion', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('codigo', models.CharField(help_text='Código del concepto (ej: VAR, ALQ, EXP, FAC, HON)', max_length=10, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción del concepto (ej: Varios, Alquileres, Expensas, etc.)', max_length=100, verbose_name='Descripción')),
                ('guid', models.CharField(help_text='GUID del concepto en Agilpagos', max_length=36, verbose_name='GUID')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Concepto Transacción',
                'verbose_name_plural': 'SG Conceptos Transacciones',
                'db_table': 'sg_concepto_transaccion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SgCondicionFiscal',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_condicion_fiscal', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Condición Fiscal')),
                ('estatus_sg_condicion_fiscal', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(help_text='Condición fiscal (ej: Consumidor Final, Responsable Inscripto, etc.)', max_length=100, verbose_name='Descripción')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Condición Fiscal',
                'verbose_name_plural': 'SG Condiciones Fiscales',
                'db_table': 'sg_condicion_fiscal',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SgEstadoCivil',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_estado_civil', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Estado Civil')),
                ('estatus_sg_estado_civil', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(help_text='Estado civil (ej: Soltero, Casado, Divorciado, Viudo, etc.)', max_length=50, verbose_name='Descripción')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Estado Civil',
                'verbose_name_plural': 'SG Estados Civiles',
                'db_table': 'sg_estado_civil',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SgEstadoTransaccion',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_estado_transaccion', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Estado Transacción')),
                ('estatus_sg_estado_transaccion', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('codigo', models.CharField(help_text='Código del estado (ej: Procesado, Pendiente, Error)', max_length=50, verbose_name='Código')),
                ('descripcion', models.CharField(help_text='Descripción del estado', max_length=100, verbose_name='Descripción')),
                ('es_final', models.BooleanField(default=False, help_text='Indica si es un estado final (terminó el proceso)', verbose_name='Es Estado Final')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Estado Transacción',
                'verbose_name_plural': 'SG Estados Transacciones',
                'db_table': 'sg_estado_transaccion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='SgMotivoPEP',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_motivo_pep', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Motivo PEP')),
                ('estatus_sg_motivo_pep', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(help_text='Motivo por el cual es Persona Expuesta Políticamente', max_length=100, verbose_name='Descripción')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Motivo PEP',
                'verbose_name_plural': 'SG Motivos PEP',
                'db_table': 'sg_motivo_pep',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SgNacionalidad',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_nacionalidad', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Nacionalidad')),
                ('estatus_sg_nacionalidad', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(help_text='Nombre de la nacionalidad (ej: Argentina, Uruguaya, etc.)', max_length=100, verbose_name='Descripción')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Nacionalidad',
                'verbose_name_plural': 'SG Nacionalidades',
                'db_table': 'sg_nacionalidad',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SgOcupacion',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_ocupacion', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Ocupación')),
                ('estatus_sg_ocupacion', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(help_text='Ocupación (ej: Comerciante, Empleado, Profesional, etc.)', max_length=100, verbose_name='Descripción')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Ocupación',
                'verbose_name_plural': 'SG Ocupaciones',
                'db_table': 'sg_ocupacion',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SgProvincia',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_provincia', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Provincia')),
                ('estatus_sg_provincia', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('codigo_iso', models.CharField(blank=True, help_text='Código ISO de la provincia (ej: AR-K)', max_length=10, null=True, verbose_name='Código ISO')),
                ('nombre_provincia', models.CharField(help_text='Nombre de la provincia (ej: Catamarca, Buenos Aires, etc.)', max_length=100, verbose_name='Nombre Provincia')),
                ('id_pais', models.CharField(help_text='GUID del país (siempre Argentina: AC98A1E7-CF65-4430-BF16-24439F35853B)', max_length=36, verbose_name='ID País')),
                ('nombre_pais', models.CharField(blank=True, help_text='Nombre del país (ej: Argentina)', max_length=60, null=True, verbose_name='Nombre País')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Provincia',
                'verbose_name_plural': 'SG Provincias',
                'db_table': 'sg_provincia',
                'ordering': ['nombre_provincia'],
            },
        ),
    ]
