# Generated by Django 6.0.6 on 2026-06-19 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0003_sgconceptotransaccion_sgcondicionfiscal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentamutual',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='cuentamutual',
            name='sexo',
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='altura',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Altura'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='apellido',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='calle',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='cp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='departamento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='es_pep',
            field=models.BooleanField(default=False, help_text='Persona Expuesta Políticamente', verbose_name='PEP'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='es_uif',
            field=models.BooleanField(default=False, help_text='Sujeto Obligado ante UIF', verbose_name='Sujeto UIF'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='fecha_alta',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario')], max_length=1, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_condicion_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_condicion_fiscal', to='maestros.sgcondicionfiscal', verbose_name='Condición Fiscal'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_estado_civil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_estado_civil', to='maestros.sgestadocivil', verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_motivo_pep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_motivo_pep', to='maestros.sgmotivopep', verbose_name='Motivo PEP'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_nacionalidad', to='maestros.sgnacionalidad', verbose_name='Nacionalidad'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_ocupacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_ocupacion', to='maestros.sgocupacion', verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_pais_domicilio',
            field=models.CharField(blank=True, default='76B19E61-B8DC-40F4-BFAB-422CBFFE5002', help_text='GUID de Argentina (fijo)', max_length=36, null=True, verbose_name='País de Domicilio'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_pais_nacimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_pais_nacimiento', to='maestros.sgnacionalidad', verbose_name='País de Nacimiento'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='id_provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_provincia', to='maestros.sgprovincia', verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='ley_fatca',
            field=models.BooleanField(default=False, help_text='Sujeto a Ley FATCA', verbose_name='Ley FATCA'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='nombre',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='numero_cuenta_entidad',
            field=models.CharField(blank=True, help_text='Identificador único asignado por la Entidad (NO reutilizable)', max_length=50, null=True, unique=True, verbose_name='Número de Cuenta Entidad'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='numero_tramite_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Trámite'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='observaciones_domicilio',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Domicilio'),
        ),
        migrations.AddField(
            model_name='cuentamutual',
            name='piso',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='alias',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Alias'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='caracteristica_pais_telefono',
            field=models.CharField(blank=True, default='54', max_length=2, null=True, verbose_name='Característica País'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='codigo_area_telefono',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Código Área'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='cvu',
            field=models.CharField(blank=True, max_length=22, null=True, unique=True, verbose_name='CVU'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='id_sg_cuenta',
            field=models.CharField(blank=True, help_text='idUsuarioEntidadLineasCuentas devuelto por Agilpagos', max_length=36, null=True, unique=True, verbose_name='ID SG Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='id_sg_usuario',
            field=models.CharField(blank=True, help_text='idUsuario devuelto por Agilpagos (¡GUARDAR!)', max_length=36, null=True, unique=True, verbose_name='ID SG Usuario'),
        ),
        migrations.AlterField(
            model_name='cuentamutual',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número Teléfono'),
        ),
        migrations.AddConstraint(
            model_name='cuentamutual',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('email',), name='uniq_email_not_null'),
        ),
        migrations.AddConstraint(
            model_name='cuentamutual',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_cuenta_entidad__isnull', False)), fields=('numero_cuenta_entidad',), name='uniq_numero_cuenta_entidad_not_null'),
        ),
    ]
