# Generated by Django 6.0.6 on 2026-10-01 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0004_remove_cuentamutual_documento_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cuentamutual',
            name='uniq_id_sg_usuario_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='cuentamutual',
            name='uniq_id_sg_cuenta_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='cuentamutual',
            name='uniq_cvu_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='cuentamutual',
            name='uniq_email_not_null',
        ),
        migrations.RemoveConstraint(
            model_name='cuentamutual',
            name='uniq_numero_cuenta_entidad_not_null',
        ),
        migrations.DeleteModel(
            name='CuentaMutual',
        ),
    ]
