# Generated by Django 6.0.6 on 2026-10-01 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0005_remove_cuentamutual_uniq_id_sg_usuario_not_null_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sgestadotransaccion',
            name='es_exitoso',
            field=models.BooleanField(default=False, help_text='Indica si es un estado exitoso (el proceso terminó correctamente)', verbose_name='Es Exitoso'),
        ),
        migrations.CreateModel(
            name='SgAmbienteAgilpagos',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_ambiente_agilpagos', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estatus_sg_ambiente_agilpagos', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('nombre', models.CharField(max_length=10, unique=True, verbose_name='Nombre')),
                ('url_base', models.CharField(max_length=255, verbose_name='URL Base')),
                ('url_onboarding', models.CharField(max_length=255, verbose_name='URL Onboarding')),
                ('url_swagger', models.CharField(max_length=255, verbose_name='URL Swagger')),
                ('id_entidad', models.CharField(max_length=36, verbose_name='ID Entidad')),
                ('id_entidad_tipo_documento', models.CharField(max_length=36, verbose_name='ID Entidad Tipo Documento')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Ambiente Agilpagos',
                'verbose_name_plural': 'SG Ambientes Agilpagos',
                'db_table': 'sg_ambiente_agilpagos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SgConstanteAgilpagos',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('clave', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('estatus_sg_constante_agilpagos', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('valor', models.CharField(max_length=36, verbose_name='Valor')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Constante Agilpagos',
                'verbose_name_plural': 'SG Constantes Agilpagos',
                'db_table': 'sg_constante_agilpagos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SgTipoCuentaMutual',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_tipo_cuenta_mutual', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estatus_sg_tipo_cuenta_mutual', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('codigo_letra', models.CharField(max_length=1, unique=True, verbose_name='Código Letra')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripción')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Tipo Cuenta Mutual',
                'verbose_name_plural': 'SG Tipos Cuentas Mutuales',
                'db_table': 'sg_tipo_cuenta_mutual',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SgTipoImpuesto',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_tipo_impuesto', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Tipo Impuesto')),
                ('estatus_sg_tipo_impuesto', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(help_text='Descripción del tipo de impuesto (ej: Impuesto SIRCUPA, Impuesto Ley 25.413, etc.)', max_length=60, verbose_name='Descripción')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Tipo Impuesto',
                'verbose_name_plural': 'SG Tipos Impuestos',
                'db_table': 'sg_tipo_impuesto',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SgTipoOperacionAviso',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_sg_tipo_operacion_aviso', models.CharField(max_length=36, primary_key=True, serialize=False, verbose_name='ID SG Tipo Operación Aviso')),
                ('estatus_sg_tipo_operacion_aviso', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(help_text='Descripción del tipo de Operación de Aviso', max_length=60, verbose_name='Descripción')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'SG Tipo Operación Aviso',
                'verbose_name_plural': 'SG Tipos Operación Avisos',
                'db_table': 'sg_tipo_operacion_aviso',
                'ordering': ['descripcion'],
            },
        ),
    ]
