# Generated by Django 6.0.6 on 2026-10-01 07:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0006_sgestadotransaccion_es_exitoso_sgambienteagilpagos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_socio', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('codigo_socio', models.IntegerField(help_text='Código de socio dentro de la sucursal (hasta 6 dígitos).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)], verbose_name='Código Socio')),
                ('id_socio_mutual', models.BigIntegerField(db_index=True, editable=False, help_text='Calculado: id_sucursal * 1.000.000 + codigo_socio.', unique=True, verbose_name='ID Socio Mutual')),
                ('id_usuario_agilpagos', models.CharField(blank=True, help_text='idUsuario devuelto por Agilpagos en el alta (UUID).', max_length=36, null=True, unique=True, verbose_name='ID Usuario Agilpagos')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('razon_social', models.CharField(blank=True, help_text='Solo para Persona Jurídica.', max_length=80, null=True, verbose_name='Razón Social')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario')], max_length=1, null=True, verbose_name='Género')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('numero_documento', models.CharField(help_text='DNI, sin prefijo F/M.', max_length=15, unique=True, verbose_name='Número de Documento')),
                ('numero_tramite_documento', models.CharField(help_text='Impreso en el DNI.', max_length=20, verbose_name='Número de Trámite')),
                ('cuit', models.BigIntegerField(unique=True, verbose_name='CUIT')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Email')),
                ('caracteristica_pais', models.CharField(blank=True, default='54', max_length=5, null=True, verbose_name='Característica País')),
                ('codigo_area', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Área')),
                ('numero_telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono')),
                ('es_pep', models.BooleanField(default=False, verbose_name='PEP')),
                ('es_uif', models.BooleanField(default=False, verbose_name='Sujeto UIF')),
                ('ley_fatca', models.BooleanField(default=False, verbose_name='Ley FATCA')),
                ('id_pais_domicilio', models.CharField(default='76b19e61-b8dc-40f4-bfab-422cbffe5002', editable=False, help_text='GUID fijo de Argentina (restricción de Agilpagos).', max_length=36, verbose_name='País de Domicilio')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('calle', models.CharField(blank=True, max_length=150, null=True, verbose_name='Calle')),
                ('altura', models.CharField(blank=True, max_length=20, null=True, verbose_name='Altura')),
                ('cp', models.CharField(blank=True, max_length=15, null=True, verbose_name='Código Postal')),
                ('piso', models.CharField(blank=True, max_length=10, null=True, verbose_name='Piso')),
                ('departamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='Departamento')),
                ('observaciones_domicilio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones Domicilio')),
                ('fecha_alta_agilpagos', models.DateField(blank=True, null=True, verbose_name='Fecha Alta Agilpagos')),
                ('id_condicion_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_condicion_fiscal', to='maestros.sgcondicionfiscal', verbose_name='Condición Fiscal')),
                ('id_entidad_tipo_documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_entidad_tipo_documento', to='maestros.sgentidadtipodocumento', verbose_name='Entidad Tipo Documento')),
                ('id_estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_estado_civil', to='maestros.sgestadocivil', verbose_name='Estado Civil')),
                ('id_motivo_pep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_motivo_pep', to='maestros.sgmotivopep', verbose_name='Motivo PEP')),
                ('id_nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_nacionalidad', to='maestros.sgnacionalidad', verbose_name='Nacionalidad')),
                ('id_ocupacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_ocupacion', to='maestros.sgocupacion', verbose_name='Ocupación')),
                ('id_pais_nacimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_pais_nacimiento', to='maestros.sgnacionalidad', verbose_name='País de Nacimiento')),
                ('id_provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_provincia', to='maestros.sgprovincia', verbose_name='Provincia')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='socios', to='maestros.sucursal', verbose_name='Sucursal')),
                ('id_tipo_persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_tipo_persona', to='maestros.sgtipopersona', verbose_name='Tipo de Persona')),
                ('id_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='socio', to=settings.AUTH_USER_MODEL)),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'socio',
                'ordering': ['id_socio_mutual'],
                'constraints': [models.UniqueConstraint(fields=('id_sucursal', 'codigo_socio'), name='uq_socio_sucursal_codigo')],
            },
        ),
    ]
