# Generated by Django 6.0.6 on 2026-10-01 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0007_socio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaCvu',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_cvu', models.AutoField(primary_key=True, serialize=False, verbose_name='ID CVU')),
                ('numero_cuenta_entidad', models.CharField(blank=True, help_text='Definido por la Mutual. Convención: id_socio_mutual + letra de tipo de cuenta. Se autogenera si no se especifica.', max_length=30, unique=True, verbose_name='Número de Cuenta Entidad')),
                ('cvu', models.CharField(help_text='Clave Virtual Uniforme (22 dígitos).', max_length=22, unique=True, verbose_name='CVU')),
                ('alias', models.CharField(blank=True, help_text='Alias del CVU (máx. 20 caracteres).', max_length=20, null=True, unique=True, verbose_name='Alias')),
                ('id_cvu2', models.CharField(blank=True, help_text="GUID 'id' devuelto por GET /CVU. Usado para Saldos/Movimientos.", max_length=36, null=True, unique=True, verbose_name='ID CVU (Agilpagos)')),
                ('id_usuario_entidad_lineas_cuentas', models.CharField(blank=True, help_text='GUID devuelto en el alta. Usado en algunos endpoints.', max_length=36, null=True, verbose_name='ID Usuario Entidad Líneas Cuentas')),
                ('estado_vcu', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Cerrado', 'Cerrado'), ('Inactivo por usuario', 'Inactivo por usuario')], default='Activo', max_length=30, verbose_name='Estado VCU')),
                ('favorita', models.BooleanField(default=False, help_text='Cuenta por defecto del socio.', verbose_name='Favorita')),
                ('bloqueada_compliance', models.BooleanField(default=False, help_text='Ver tabla evento_novedad_cvu.', verbose_name='Bloqueada por Compliance')),
                ('fecha_alta', models.DateField(blank=True, null=True, verbose_name='Fecha de Alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de Baja')),
                ('id_motivo_baja', models.CharField(blank=True, help_text='GUID del motivo de baja (catálogo pendiente de definir).', max_length=36, null=True, verbose_name='ID Motivo de Baja')),
                ('observaciones_baja', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones de Baja')),
                ('alias_actualizado_at', models.DateTimeField(blank=True, help_text='Controla la regla de 24hs entre cambios de alias.', null=True, verbose_name='Alias Actualizado En')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cvu', to='maestros.socio', verbose_name='Socio')),
                ('id_tipo_cuenta_mutual', models.ForeignKey(help_text='Distingue si esta CVU corresponde a la caja C, E o D del socio.', on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_cvu', to='maestros.sgtipocuentamutual', verbose_name='Tipo de Cuenta Mutual')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'Cuenta CVU',
                'verbose_name_plural': 'Cuentas CVU',
                'db_table': 'cuenta_cvu',
                'ordering': ['id_cvu'],
                'indexes': [models.Index(fields=['id_socio'], name='ix_cvu_socio'), models.Index(fields=['estado_vcu'], name='ix_cvu_estado'), models.Index(fields=['id_tipo_cuenta_mutual'], name='ix_cvu_tipo_cuenta')],
                'constraints': [models.UniqueConstraint(fields=('id_socio', 'id_tipo_cuenta_mutual'), name='uq_cvu_socio_tipo_cuenta')],
            },
        ),
    ]
