# Generated by Django 6.0.6 on 2026-10-01 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0008_cuentacvu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CvuAliasHistorial',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fcontrol2', models.DateTimeField(auto_now=True, null=True)),
                ('id_cvu_alias_historial', models.AutoField(primary_key=True, serialize=False, verbose_name='ID CVU Alias Historial')),
                ('alias_anterior', models.CharField(blank=True, help_text='Puede ser nulo si es el primer alias asignado.', max_length=20, null=True, verbose_name='Alias Anterior')),
                ('alias_nuevo', models.CharField(help_text='Alias asignado en este cambio.', max_length=20, verbose_name='Alias Nuevo')),
                ('origen', models.CharField(choices=[('MUTUAL', 'Mutual'), ('COELSA_AUTOMATICO', 'Coelsa (Automático)')], default='MUTUAL', help_text='Quién originó el cambio: la Mutual o Coelsa automáticamente.', max_length=20, verbose_name='Origen')),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now, help_text='Momento en que se registró el cambio de alias.', verbose_name='Fecha de Cambio')),
                ('id_cvu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_historial', to='maestros.cuentacvu', verbose_name='CVU')),
                ('id_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
                ('id_user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador')),
            ],
            options={
                'verbose_name': 'CVU Alias Historial',
                'verbose_name_plural': 'CVU Alias Historiales',
                'db_table': 'cvu_alias_historial',
                'ordering': ['-fecha_cambio', '-id_cvu_alias_historial'],
                'indexes': [models.Index(fields=['id_cvu'], name='ix_cvu_alias_hist_cvu'), models.Index(fields=['fecha_cambio'], name='ix_cvu_alias_hist_fecha')],
            },
        ),
    ]
