# Generated by Django 6.0.6 on 2026-10-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0009_cvualiashistorial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentacvu',
            options={'ordering': ['id_cuenta_cvu'], 'verbose_name': 'Cuenta CVU', 'verbose_name_plural': 'Cuentas CVU'},
        ),
        migrations.RenameField(
            model_name='cuentacvu',
            old_name='id_cvu',
            new_name='id_cuenta_cvu',
        ),
        migrations.RenameField(
            model_name='cuentacvu',
            old_name='id_cvu2',
            new_name='id_cvu_agilpagos',
        ),
    ]
