# Generated by Django 6.0.6 on 2026-10-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0010_renombrar_campos_cvu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuentacvu',
            old_name='id_cvu_agilpagos',
            new_name='id_cvu',
        ),
    ]
