# Generated by Django 6.0.6 on 2026-10-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0011_rename_id_cvu_agilpagos_cuentacvu_id_cvu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='id_socio_mutual',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Calculado automáticamente: id_sucursal * 1.000.000 + codigo_socio.', null=True, unique=True, verbose_name='ID Socio Mutual'),
        ),
    ]
