# Generated by Django 6.0.6 on 2026-10-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0012_alter_socio_id_socio_mutual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='id_entidad_tipo_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='socios_entidad_tipo_documento', to='maestros.sgentidadtipodocumento', verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='numero_documento',
            field=models.CharField(help_text='DNI, sin prefijo F/M.', max_length=15, unique=True, verbose_name='Número Documento'),
        ),
    ]
