# Generated by Django 6.0.6 on 2026-10-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0013_alter_socio_id_entidad_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentacvu',
            name='cvu',
            field=models.CharField(blank=True, help_text='Clave Virtual Uniforme (22 dígitos).', max_length=22, null=True, unique=True, verbose_name='CVU'),
        ),
    ]
