# Generated by Django 6.0.6 on 2026-10-06 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0011_rename_id_cvu_agilpagos_cuentacvu_id_cvu'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashoutRequest',
            fields=[
                ('id_cashout_request', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_transaccion_entidad', models.UUIDField(db_index=True, help_text='UUID v7 generado por la API Intermedia.', unique=True)),
                ('cvu_debito', models.CharField(db_index=True, help_text='CVU de la cuenta origen.', max_length=22)),
                ('numero_cuenta_entidad', models.CharField(db_index=True, help_text='numeroCuentaEntidad de la CVU origen.', max_length=30)),
                ('cuit_credito', models.BigIntegerField(verbose_name='CUIT del beneficiario')),
                ('cbu_credito', models.CharField(max_length=22, verbose_name='CVU/CBU del beneficiario')),
                ('nombre_credito', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre del beneficiario')),
                ('importe', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('id_concepto', models.ForeignKey(db_column='id_concepto', on_delete=django.db.models.deletion.PROTECT, to='maestros.sgconceptotransaccion')),
            ],
            options={
                'verbose_name': 'Cashout Request',
                'verbose_name_plural': 'Cashout Requests',
                'db_table': 'cashout_request',
                'ordering': ['-creado_at'],
            },
        ),
        migrations.CreateModel(
            name='CashoutResponse',
            fields=[
                ('id_cashout_response', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_debito', models.UUIDField(blank=True, null=True)),
                ('error_coelsa_debito', models.CharField(blank=True, max_length=255, null=True)),
                ('total_debito', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('id_credito', models.UUIDField(blank=True, null=True)),
                ('error_coelsa_credito', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credito', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('id_coelsa', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('id_estado_credito', models.ForeignKey(blank=True, db_column='id_estado_credito', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashout_response_credito', to='maestros.sgestadotransaccion')),
                ('id_estado_debito', models.ForeignKey(blank=True, db_column='id_estado_debito', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashout_response_debito', to='maestros.sgestadotransaccion')),
                ('id_transaccion_entidad', models.OneToOneField(db_column='id_transaccion_entidad', on_delete=django.db.models.deletion.PROTECT, related_name='response', to='transacciones.cashoutrequest', to_field='id_transaccion_entidad')),
            ],
            options={
                'verbose_name': 'Cashout Response',
                'verbose_name_plural': 'Cashout Responses',
                'db_table': 'cashout_response',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_transaccion_entidad', models.UUIDField(db_index=True, help_text='UUID v7 generado por la API Intermedia. Agrupa todos los movimientos de una misma transacción.')),
                ('tipo_movimiento', models.CharField(choices=[('CASH_OUT', 'CASH_OUT'), ('CASH_IN', 'CASH_IN'), ('REVERSA', 'REVERSA'), ('IMPUESTO', 'IMPUESTO'), ('AJUSTE', 'AJUSTE')], max_length=20)),
                ('numero_cuenta_entidad', models.CharField(db_index=True, help_text='numeroCuentaEntidad de la CVU afectada.', max_length=30)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('conciliado_at', models.DateTimeField(blank=True, null=True)),
                ('sincronizado_vfp', models.BooleanField(default=False)),
                ('sincronizado_vfp_at', models.DateTimeField(blank=True, null=True)),
                ('comprobante_vfp_id', models.BigIntegerField(blank=True, null=True)),
                ('id_transaccion_agilpagos', models.BigIntegerField(blank=True, null=True)),
                ('id_transaccion_coelsa', models.CharField(blank=True, db_index=True, max_length=60, null=True)),
                ('observaciones', models.CharField(blank=True, default='', max_length=255)),
                ('id_cuenta_cvu', models.ForeignKey(blank=True, db_column='id_cuenta_cvu', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='maestros.cuentacvu')),
                ('id_estado_transaccion', models.ForeignKey(blank=True, db_column='id_estado_transaccion', null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sgestadotransaccion')),
                ('id_socio', models.ForeignKey(blank=True, db_column='id_socio', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='maestros.socio')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimiento',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoImpuesto',
            fields=[
                ('id_movimiento_impuesto', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_transaccion_entidad', models.UUIDField(db_index=True, help_text='UUID v7 de la transacción originante (CashoutRequest).')),
                ('id_transaccion_impuesto', models.UUIDField(help_text='ID de la retención en sí (Agilpagos).')),
                ('id_transaccion_originante', models.UUIDField(help_text='A qué transacción de crédito/débito se vincula.')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_tipo_transaccion', models.SmallIntegerField(help_text='1=Débito 2=Crédito 3=Reversa débito 4=Reversa crédito')),
                ('id_web_operacion', models.ForeignKey(db_column='id_web_operacion', on_delete=django.db.models.deletion.PROTECT, to='maestros.sgtipoimpuesto')),
            ],
            options={
                'verbose_name': 'Movimiento Impuesto',
                'verbose_name_plural': 'Movimientos Impuestos',
                'db_table': 'movimiento_impuesto',
                'ordering': ['-id_movimiento_impuesto'],
            },
        ),
        migrations.CreateModel(
            name='SaldoCvu',
            fields=[
                ('id_saldo_cvu', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_cuenta_entidad', models.CharField(db_index=True, max_length=30, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, help_text='Saldo contable de la CVU (ya refleja las operaciones en estado final).', max_digits=15)),
                ('saldo_retenido', models.DecimalField(decimal_places=2, default=0.0, help_text='Importe retenido por transacciones pendientes de confirmación.', max_digits=15)),
                ('actualizado_at', models.DateTimeField(auto_now=True)),
                ('id_cuenta_cvu', models.OneToOneField(db_column='id_cuenta_cvu', on_delete=django.db.models.deletion.PROTECT, related_name='saldo', to='maestros.cuentacvu')),
                ('id_socio', models.ForeignKey(db_column='id_socio', on_delete=django.db.models.deletion.PROTECT, related_name='saldos_cvu', to='maestros.socio')),
            ],
            options={
                'verbose_name': 'Saldo Cvu',
                'verbose_name_plural': 'Saldos Cvu',
                'db_table': 'saldo_cvu',
            },
        ),
        migrations.AddIndex(
            model_name='cashoutrequest',
            index=models.Index(fields=['id_transaccion_entidad'], name='ix_coutreq_trx'),
        ),
        migrations.AddIndex(
            model_name='cashoutrequest',
            index=models.Index(fields=['cvu_debito'], name='ix_coutreq_cvu'),
        ),
        migrations.AddIndex(
            model_name='cashoutresponse',
            index=models.Index(fields=['id_transaccion_entidad'], name='ix_coutres_trx'),
        ),
        migrations.AddIndex(
            model_name='cashoutresponse',
            index=models.Index(fields=['id_coelsa'], name='ix_coutres_coelsa'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['id_transaccion_entidad'], name='ix_mov_trx_entidad'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['numero_cuenta_entidad'], name='ix_mov_nro_cta'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['fecha'], name='ix_mov_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo_movimiento'], name='ix_mov_tipo'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['conciliado'], name='ix_mov_conciliado'),
        ),
        migrations.AddIndex(
            model_name='movimientoimpuesto',
            index=models.Index(fields=['id_transaccion_entidad'], name='ix_movimp_trx'),
        ),
        migrations.AddConstraint(
            model_name='movimientoimpuesto',
            constraint=models.UniqueConstraint(fields=('id_transaccion_impuesto',), name='uniq_movimiento_impuesto_transaccion'),
        ),
        migrations.AddIndex(
            model_name='saldocvu',
            index=models.Index(fields=['numero_cuenta_entidad'], name='ix_saldo_nro_cta'),
        ),
    ]
