# Generated by Django 6.0.6 on 2026-10-02 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0011_rename_id_cvu_agilpagos_cuentacvu_id_cvu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('CASH_OUT', 'CASH_OUT'), ('CASH_IN', 'CASH_IN'), ('REVERSA', 'REVERSA'), ('IMPUESTO', 'IMPUESTO'), ('AJUSTE', 'AJUSTE')], max_length=20)),
                ('numero_cuenta_entidad', models.CharField(max_length=30, unique=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('sincronizado_vfp', models.BooleanField(default=False)),
                ('sincronizado_vfp_at', models.DateTimeField(blank=True, null=True)),
                ('comprobante_vfp_id', models.BigIntegerField(blank=True, null=True)),
                ('id_transaccion_agilpagos', models.BigIntegerField(blank=True, null=True)),
                ('observaciones', models.CharField(max_length=255)),
                ('id_cuenta_cvu', models.ForeignKey(blank=True, db_column='id_cuenta_cvu', null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.cuentacvu')),
                ('id_estado_transaccion', models.ForeignKey(blank=True, db_column='id_estado_transaccion', null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sgestadotransaccion')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimiento',
            },
        ),
        migrations.CreateModel(
            name='CashoutResponse',
            fields=[
                ('id_cashout_response', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_debito', models.UUIDField(blank=True, null=True)),
                ('error_coelsa_debito', models.CharField(blank=True, max_length=255, null=True)),
                ('total_debito', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('id_credito', models.UUIDField(blank=True, null=True)),
                ('error_coelsa_credito', models.CharField(blank=True, max_length=255, null=True)),
                ('total_credito', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('id_coelsa', models.CharField(blank=True, max_length=60, null=True)),
                ('id_estado_credito', models.ForeignKey(blank=True, db_column='id_estado_credito', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashout_response_credito', to='maestros.sgestadotransaccion')),
                ('id_estado_debito', models.ForeignKey(blank=True, db_column='id_estado_debito', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashout_response_debito', to='maestros.sgestadotransaccion')),
                ('id_movimiento', models.ForeignKey(blank=True, db_column='id_movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.movimiento')),
            ],
            options={
                'verbose_name': 'Cashout Response',
                'verbose_name_plural': 'Cashout Responses',
                'db_table': 'cashout_response',
            },
        ),
        migrations.CreateModel(
            name='CashoutRequest',
            fields=[
                ('id_cashout_request', models.BigAutoField(primary_key=True, serialize=False)),
                ('cuit_credito', models.BigIntegerField(verbose_name='CUIT del beneficiario')),
                ('cbu_credito', models.CharField(max_length=22, verbose_name='CVU/CBU del beneficiario')),
                ('nombre_credito', models.CharField(blank=True, max_length=40, null=True, verbose_name='Nombre del beneficiario')),
                ('importe', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('observaciones', models.CharField(max_length=255)),
                ('id_transaccion_entidad', models.UUIDField()),
                ('creado_at', models.DateTimeField(auto_now_add=True)),
                ('id_concepto', models.ForeignKey(db_column='id_concepto', on_delete=django.db.models.deletion.PROTECT, to='maestros.sgconceptotransaccion')),
                ('id_movimiento', models.ForeignKey(db_column='id_movimiento', on_delete=django.db.models.deletion.PROTECT, to='transacciones.movimiento')),
            ],
            options={
                'verbose_name': 'Cashout Request',
                'verbose_name_plural': 'Cashout Requests',
                'db_table': 'cashout_request',
            },
        ),
        migrations.CreateModel(
            name='CashinRequest',
            fields=[
                ('id_cashin_request', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_transaccion', models.UUIDField(blank=True, null=True)),
                ('id_transaccion_anulada', models.UUIDField(blank=True, null=True)),
                ('id_transaccion_originante', models.BigIntegerField(blank=True, null=True)),
                ('id_transaccion_entidad', models.BigIntegerField(blank=True, null=True)),
                ('id_entidad', models.UUIDField(blank=True, null=True)),
                ('id_tipo_transaccion', models.SmallIntegerField(blank=True, help_text='1: Débito; 2: Crédito; 3: Reversa Débito; 4: Reversa Crédito', null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('id_moneda', models.SmallIntegerField(default=1)),
                ('fecha_operacion', models.DateTimeField()),
                ('fecha_contable', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_cuenta', models.CharField(max_length=30)),
                ('cvu', models.CharField(max_length=22)),
                ('cuenta_bloqueada', models.BooleanField(default=False)),
                ('id_coelsa', models.CharField(blank=True, max_length=60, null=True)),
                ('cuenta_contraparte', models.CharField(blank=True, max_length=30, null=True)),
                ('cuit_contraparte', models.BigIntegerField(blank=True, null=True)),
                ('titular_contraparte', models.CharField(blank=True, max_length=40, null=True)),
                ('id_web_operacion', models.ForeignKey(blank=True, db_column='id_web_operacion', null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.sgtipooperacionaviso')),
                ('id_movimiento', models.ForeignKey(blank=True, db_column='id_movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.movimiento')),
            ],
            options={
                'verbose_name': 'Cashin Request',
                'verbose_name_plural': 'Cashin Requests',
                'db_table': 'cashin_request',
            },
        ),
        migrations.CreateModel(
            name='SaldoCvu',
            fields=[
                ('id_saldo_cvu', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_cuenta_entidad', models.CharField(max_length=30, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_cuenta_cvu', models.ForeignKey(db_column='id_cuenta_cvu', on_delete=django.db.models.deletion.PROTECT, to='maestros.cuentacvu')),
                ('id_socio', models.ForeignKey(db_column='id_socio', on_delete=django.db.models.deletion.PROTECT, to='maestros.socio')),
            ],
            options={
                'verbose_name': 'Saldo Cvu',
                'verbose_name_plural': 'Saldos Cvu',
                'db_table': 'saldo_cvu',
            },
        ),
        migrations.CreateModel(
            name='MovimientoImpuesto',
            fields=[
                ('id_movimiento_impuesto', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_transaccion_impuesto', models.UUIDField(help_text='id de la retención en sí (Agilpagos)')),
                ('id_transaccion_originante', models.UUIDField(help_text='a qué transacción de crédito/débito se vincula')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_tipo_transaccion', models.SmallIntegerField(help_text='1=Débito 2=Crédito 3=Reversa débito 4=Reversa crédito')),
                ('id_movimiento', models.ForeignKey(blank=True, db_column='id_movimiento', null=True, on_delete=django.db.models.deletion.PROTECT, to='transacciones.movimiento')),
                ('id_web_operacion', models.ForeignKey(db_column='id_web_operacion', on_delete=django.db.models.deletion.PROTECT, to='maestros.sgtipoimpuesto')),
            ],
            options={
                'verbose_name': 'Movimiento Impuesto',
                'verbose_name_plural': 'Movimientos Impuesto',
                'db_table': 'movimiento_impuesto',
                'constraints': [models.UniqueConstraint(fields=('id_transaccion_impuesto',), name='uniq_movimiento_impuesto_transaccion')],
            },
        ),
    ]
