# Generated by Django 6.0.6 on 2026-10-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='id_transaccion_agilpagos',
            field=models.CharField(blank=True, db_index=True, help_text="GUID 'id' devuelto por Agilpagos en la respuesta de la transacción.", max_length=36, null=True),
        ),
    ]
