# Generated by Django 6.0.6 on 2026-10-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transacciones', '0002_alter_movimiento_id_transaccion_agilpagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutrequest',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cashoutrequest',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
